#!/bin/sh
# shutdown - runit compatible shutdown command
case "$1" in
    -h|--halt|-P|--poweroff)
        touch /etc/runit/stopit
        chmod 0 /etc/runit/stopit
        kill -CONT 1
        ;;
    -r|--reboot)
        touch /etc/runit/stopit
        chmod 100 /etc/runit/stopit
        touch /etc/runit/reboot
        kill -CONT 1
        ;;
    now)
        touch /etc/runit/stopit
        chmod 0 /etc/runit/stopit
        kill -CONT 1
        ;;
    *)
        echo "Usage: shutdown [-h|-r|now]"
        echo "  -h, --halt, -P  Halt the system"
        echo "  -r, --reboot    Reboot the system"
        echo "  now             Halt immediately"
        exit 1
        ;;
esac
